### ISSUE TITLE
How do I upload video from URI

### ISSUE THREAD

**Issue by intellij-Shivam** [RobinBobin/react-native-google-drive-api-wrapper#24]
I'm not able to upload the media(video) other the Base64 format, base64 is causing app crash, due to over file size, can you please tell me how should I upload it to google drive

**Comment by RobinBobin** [comment]
I guess, [createFileMultipart()](https://github.com/RobinBobin/react-native-google-drive-api-wrapper#gdriveapiwFiles) is your choice. The first param will be a binary buffer with your video, the second - mime, and pass ```false``` as the fourth.

**Comment by RobinBobin** [comment]
I'll close the issue, as it's been inactive for a while.

**Comment by RobinBobin** [comment]
I'll close the issue as it's been inactive for a while.

**Comment by sintylapse** [comment]
@RobinBobin how exactly can I get a file as a binary buffer? any info would be helpful

**Comment by RobinBobin** [comment]
Well, it can get pretty messy in RN :disappointed: . [react-native-fs](https://www.npmjs.com/package/react-native-fs) or something similar can be used. What's your use case?

**Comment by sintylapse** [comment]
Actually I used rn-fetch-blob instead of your package in order to upload file directly from storage to Google Drive, avoiding passing file trough the bridge. The problem was in converting file to base64 string for createFileMultipart. If file is more than a few Mb, some Android phones can crash. Here is the solution https://github.com/joltup/rn-fetch-blob/issues/1#issuecomment-376526473

**Comment by RobinBobin** [comment]
I see. Well, do you have your issue sorted out or any other help is needed?

**Comment by sintylapse** [comment]
Everything is fine, thanks

**Comment by RobinBobin** [comment]
Great. I'll close then.
