### ISSUE TITLE
Regarding Download a file stored on Google Drive

### ISSUE THREAD

**Issue by RutvikUnjiya** [RobinBobin/react-native-google-drive-api-wrapper#62]
Which Method Should i use for Download the uploaded file on drive(get or getContent)?
And what should i pass as queryParameters for Download the files?i'm confused so please help me.

**Comment by RobinBobin** [comment]
Hello,

You can get file contents, but not download files with my package, since it's just a wrapper around Google Drive API.

`queryParameters` for all the `get` methods are defined here: https://developers.google.com/drive/api/v3/reference/files/get

I tried to make the docs as clear as possible. What is unclear for you in `get` / `getContents`, etc. methods description? Please tell me and I'll do my best to make it better.
